build:
  # TODO Build all targets
  # TODO Run the tests
  blinky:
    image: mynewt/newt
    commands:
      - newt install -v
      - newt build ble-nrf51

  lint:
    # We use Arch as a base because it is lightweight and ships with latest
    # uncrustify
    image: base/archlinux
    commands:
      - pacman -Sy && pacman -S --noconfirm uncrustify git grep
      - ./beautify
      # Fail if some files were changed
      - ./.ci/lint.sh
