#!/bin/sh

set -e
set -u

cd $(dirname $0)

UNCRUSTIFY_FLAGS="-c uncrustify.cfg --replace --no-backup"

# Get all the sources that are stored in Git
SRC="$(git ls-tree --full-tree -r HEAD | grep -e "\.\(h\|c\|cpp\)$" | cut -f 2)"

echo $SRC

chmod -x $SRC

# run it twice because uncrustify is not very smart
for i in $SRC; do
    uncrustify $UNCRUSTIFY_FLAGS $i || true
    uncrustify $UNCRUSTIFY_FLAGS $i || true
done
