project.name: "sun_sensor"

project.repositories:
  - apache-mynewt-core

# Grab core repo from Github (apache/incubator-mynewt-core)
repository.apache-mynewt-core:
  type: github
  vers: 0.0.0 # use develop to have stm32f4 I2C
  user: apache
  repo: incubator-mynewt-core
